// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PdxBusiness.Models;

namespace PdxBusiness.Migrations
{
    [DbContext(typeof(PdxBusinessContext))]
    [Migration("20200821182300_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PdxBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Owner");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Url");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Address = "online only",
                            Description = "Skincare for all skin types, all natural.",
                            Name = "Bahia Honey Beauty and Well-being",
                            Owner = "Bahia Overton",
                            PhoneNumber = "(503) 395-7090",
                            Url = "https://bahiahoney.com/"
                        },
                        new
                        {
                            BusinessId = 2,
                            Address = "404 NE 28th Ave, Portland, OR. 97232",
                            Description = "Vegan restaurant and pico lounge serving 'dishes inspired by the Andes region of South America, but with our own twist.' POC and woman-owned.",
                            Name = "Epif",
                            Owner = "Pepe and Nicolle",
                            PhoneNumber = "(971) 254-8680",
                            Url = "https://www.epifpdx.com/"
                        },
                        new
                        {
                            BusinessId = 3,
                            Address = "1010 SE Water Ave, Portland, OR. 97214",
                            Description = "Business providing standing desks, chairs and ergonomic furniture.",
                            Name = "Fully",
                            Owner = "David Kahl",
                            PhoneNumber = "(888) 508-3725",
                            Url = "https://www.fully.com/"
                        },
                        new
                        {
                            BusinessId = 4,
                            Address = "5521 SE Woodstock Blvd, Portland, OR. 97206",
                            Description = "Full-service traffic control and equipment rental company",
                            Name = "Chick Of All Trades, LLC",
                            Owner = "Val Solorzano",
                            PhoneNumber = "(503) 467-6386",
                            Url = "http://www.coatflagging.com/"
                        },
                        new
                        {
                            BusinessId = 5,
                            Address = "1061 Lloyd Center, Portland, OR. 97232",
                            Description = "Sports merchandise, clothing line",
                            Name = "Cultural Blends",
                            Owner = "Troy Douglass",
                            PhoneNumber = "(503) 572-9757",
                            Url = "https://www.culturalblends.net/"
                        },
                        new
                        {
                            BusinessId = 6,
                            Address = "1033 SW Yamhill St., Suite 203, Portland, OR. 97209",
                            Description = "Althernative and holistic health services, health and wellness, massage",
                            Name = "SomaFlow Health and Massage, LLC",
                            Owner = "Kristi Carlough",
                            PhoneNumber = "(503) 929-3525",
                            Url = "https://www.somaflow.health/"
                        },
                        new
                        {
                            BusinessId = 7,
                            Address = "2901 NE Alberta St. Portland, OR. 97211",
                            Description = "Woman owned, Indegenous, two-spirit-owned and operated herb shop",
                            Name = "Clary Sage Herbarium",
                            Owner = "Laurie Books",
                            PhoneNumber = "(503) 236-6737",
                            Url = "https://clarysageherbarium.com/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
