// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PdxBusiness.Models;

namespace PdxBusiness.Migrations
{
    [DbContext(typeof(PdxBusinessContext))]
    [Migration("20200821232926_ChangeResponsecs")]
    partial class ChangeResponsecs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PdxBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Owner");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Url");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Address = "online only",
                            Description = "Skincare for all skin types, all natural.",
                            Name = "Bahia Honey Beauty and Well-being",
                            Owner = "Bahia Overton",
                            PhoneNumber = "(503) 395-7090",
                            Url = "https://bahiahoney.com/"
                        },
                        new
                        {
                            BusinessId = 2,
                            Address = "404 NE 28th Ave, Portland, OR. 97232",
                            Description = "Vegan restaurant and pico lounge serving 'dishes inspired by the Andes region of South America, but with our own twist.' POC and woman-owned.",
                            Name = "Epif",
                            Owner = "Pepe and Nicolle",
                            PhoneNumber = "(971) 254-8680",
                            Url = "https://www.epifpdx.com/"
                        },
                        new
                        {
                            BusinessId = 3,
                            Address = "1010 SE Water Ave, Portland, OR. 97214",
                            Description = "Business providing standing desks, chairs and ergonomic furniture.",
                            Name = "Fully",
                            Owner = "David Kahl",
                            PhoneNumber = "(888) 508-3725",
                            Url = "https://www.fully.com/"
                        },
                        new
                        {
                            BusinessId = 4,
                            Address = "5521 SE Woodstock Blvd, Portland, OR. 97206",
                            Description = "Full-service traffic control and equipment rental company",
                            Name = "Chick Of All Trades, LLC",
                            Owner = "Val Solorzano",
                            PhoneNumber = "(503) 467-6386",
                            Url = "http://www.coatflagging.com/"
                        },
                        new
                        {
                            BusinessId = 5,
                            Address = "1061 Lloyd Center, Portland, OR. 97232",
                            Description = "Sports merchandise, clothing line",
                            Name = "Cultural Blends",
                            Owner = "Troy Douglass",
                            PhoneNumber = "(503) 572-9757",
                            Url = "https://www.culturalblends.net/"
                        },
                        new
                        {
                            BusinessId = 6,
                            Address = "1033 SW Yamhill St., Suite 203, Portland, OR. 97209",
                            Description = "Althernative and holistic health services, health and wellness, massage",
                            Name = "SomaFlow Health and Massage, LLC",
                            Owner = "Kristi Carlough",
                            PhoneNumber = "(503) 929-3525",
                            Url = "https://www.somaflow.health/"
                        },
                        new
                        {
                            BusinessId = 7,
                            Address = "2901 NE Alberta St. Portland, OR. 97211",
                            Description = "Woman owned, Indegenous, two-spirit-owned and operated herb shop",
                            Name = "Clary Sage Herbarium",
                            Owner = "Laurie Books",
                            PhoneNumber = "(503) 236-6737",
                            Url = "https://clarysageherbarium.com/"
                        });
                });

            modelBuilder.Entity("PdxBusiness.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bio");

                    b.Property<string>("Business");

                    b.Property<string>("Name");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            OwnerId = 1,
                            Bio = "Bahia Overton founded Bahia Honey after developing a moisturizure to help treat her daughters eczema, after repeatedly trying other moisturizers on the market with no success.",
                            Business = "Bahia Honey Beauty and Well-Being",
                            Name = "Bahia Overton"
                        },
                        new
                        {
                            OwnerId = 2,
                            Bio = "This couple owned and operated an international restaurant and bar for six years in Pepe's hometown of Valparaiso, Chile. After moving to Portland, they designed and created their business right in front of their very own home. The interior of their restaurant and bar is full of gems from Chile and Peru, such as the bar top!",
                            Business = "Epif",
                            Name = "Pepe and Nicolle"
                        },
                        new
                        {
                            OwnerId = 3,
                            Bio = "On September 11th, David Kahl stood on the 56th floor of his office building, four miles away from the Twin Towers in New York city. After that life changing day, he quit his job as an accountant and started down a path that led to the founding of his business, Fully.",
                            Business = "Fully",
                            Name = "David Kahl"
                        },
                        new
                        {
                            OwnerId = 4,
                            Bio = "Val Solorzano started her business in 2006 and focused initially on providing traffic control services. Her business has since grown and expanded and now has a hand in a variety of projects around Portland.",
                            Business = "Chick of All Trades, LLC",
                            Name = "Val Solorzano"
                        },
                        new
                        {
                            OwnerId = 5,
                            Bio = "Troy Douglass is a member of the Confederated Tribes of Grand Ronde who owns and operates a sports merchandise store and designs his own apparal. In one of his instagram posts at @culturalblends, he writes about the fact that he is a descendent of Chief Coboway, a Clatsop Chief.",
                            Business = "Cultural Blends",
                            Name = "Troy Douglass"
                        },
                        new
                        {
                            OwnerId = 6,
                            Bio = "Before the pandemic, Kristi Carlough was taking coaching and business classes taught by the Native American Youth and Family Center. She prioritizes creating a safe space where BIPOC can feel comfortable going for self-care.",
                            Business = "SomaFlow Health and Massage, LLC",
                            Name = "Kristi Carlough"
                        },
                        new
                        {
                            OwnerId = 7,
                            Bio = "As the Clary Sage Herbarium site states, Clary is an indigenous, two-spirit woman, providing fine quality organic herbal products and focused on promoting local awareness and offering a place of healing.",
                            Business = "Clary Sage Herbarium",
                            Name = "Laurie Books"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
